In [3]:
import pandas as pd
import numpy as np
from scipy.stats import pearsonr

##Load Data

In [7]:
df = pd.read_csv("data/final_dataset.csv")

df.head()

,year,co2,temp_anomaly,conflict_deaths,ai_publications,ai_capability,conflict_index,climate_pressure,co2_pressure,ai_safety,risk_score
0,2016,3.539283e+10,1.008333,90624,574316,0.000000,1.694912,3.690249,0.681907,1.506744,0.777945
1,2017,3.597461e+10,0.914167,72023,640509,0.580745,0.865558,1.529637,2.372956,2.120638,0.326682
2,2018,3.673400e+10,0.847500,55031,787932,1.874163,0.107944,0.000000,4.580275,4.321720,-0.155545
3,2019,3.708657e+10,0.978333,52610,967369,3.448456,0.000000,3.001912,5.605069,4.304960,1.076361
4,2020,3.515823e+10,1.005833,73228,1139600,4.959528,0.919285,3.632887,0.000000,5.026170,1.184382

In [8]:
df.describe()

,year,co2,temp_anomaly,conflict_deaths,ai_publications,ai_capability,conflict_index,climate_pressure,co2_pressure,ai_safety,risk_score
count,9.000000,9.000000e+00,9.000000,9.000000,9.000000e+00,9.000000,9.000000,9.000000,9.000000,9.000000,9.000000
mean,2020.000000,3.682594e+10,0.993796,119966.444444,1.133031e+06,4.901896,3.003190,3.356703,4.847514,4.990692,2.125345
std,2.738613,1.166232e+09,0.147945,75241.274601,4.203214e+05,3.687696,3.354747,3.394529,3.389865,2.145724,1.922158
min,2016.000000,3.515823e+10,0.847500,52610.000000,5.743160e+05,0.000000,0.000000,0.000000,0.000000,1.506744,-0.155545
25%,2018.000000,3.597461e+10,0.890000,72023.000000,7.879320e+05,1.874163,0.865558,0.975143,2.372956,4.304960,0.777945
50%,2020.000000,3.686686e+10,0.978333,90624.000000,1.139600e+06,4.959528,1.694912,3.001912,4.966451,5.026170,1.184382
75%,2022.000000,3.752777e+10,1.008333,131061.000000,1.366384e+06,6.949221,3.497858,3.690249,6.887506,6.580220,3.906949
max,2024.000000,3.859858e+10,1.283333,276893.000000,1.714110e+06,10.000000,10.000000,10.000000,10.000000,7.471744,5.179087

## Correlation Between AI Capability and Risk Score

In [6]:
corr, p_value = pearsonr(df["ai_capability"], df["risk_score"])

print("Correlation:", corr)
print("P-value:", p_value)

Correlation: 0.9282895190743263
P-value: 0.0003029720301777163

## Correlation Matrix

In [9]:
correlation_matrix = df.corr(numeric_only=True)

correlation_matrix

,year,co2,temp_anomaly,conflict_deaths,ai_publications,ai_capability,conflict_index,climate_pressure,co2_pressure,ai_safety,risk_score
year,1.000000,0.804244,0.561244,0.557660,0.992815,0.992815,0.557660,0.561244,0.804244,0.962918,0.927569
co2,0.804244,1.000000,0.502136,0.415559,0.780634,0.780634,0.415559,0.502136,1.000000,0.768622,0.801805
temp_anomaly,0.561244,0.502136,1.000000,-0.114510,0.577879,0.577879,-0.114510,1.000000,0.502136,0.390800,0.648950
conflict_deaths,0.557660,0.415559,-0.114510,1.000000,0.546002,0.546002,1.000000,-0.114510,0.415559,0.554772,0.650008
ai_publications,0.992815,0.780634,0.577879,0.546002,1.000000,1.000000,0.546002,0.577879,0.780634,0.965095,0.928290
ai_capability,0.992815,0.780634,0.577879,0.546002,1.000000,1.000000,0.546002,0.577879,0.780634,0.965095,0.928290
conflict_index,0.557660,0.415559,-0.114510,1.000000,0.546002,0.546002,1.000000,-0.114510,0.415559,0.554772,0.650008
climate_pressure,0.561244,0.502136,1.000000,-0.114510,0.577879,0.577879,-0.114510,1.000000,0.502136,0.390800,0.648950
co2_pressure,0.804244,1.000000,0.502136,0.415559,0.780634,0.780634,0.415559,0.502136,1.000000,0.768622,0.801805
ai_safety,0.962918,0.768622,0.390800,0.554772,0.965095,0.965095,0.554772,0.390800,0.768622,1.000000,0.828794
risk_score,0.927569,0.801805,0.648950,0.650008,0.928290,0.928290,0.650008,0.648950,0.801805,0.828794,1.000000